### PR TITLE
New Chrome Icon Stuff

### PR DESCRIPTION
**Pull request by bluetidepro**

### CODE REVIEW

**Comment by mrmrs** [comment]
@bluetidepro This is great thanks!

**Comment by mrmrs** [comment]
@paulmolluzzo - Hey paul - can you grab the latest icon stuff and update it on the chrome store? Let me know if I need to do anything on my end.

**Comment by paulmolluzzo** [comment]
@mrmrs I can, but first the commits from pull #16 need to be reverted. That pull request broke functionality in the extension. Can push the update today/tomorrow once I get a few minutes.

**Comment by mrmrs** [comment]
@paulmolluzzo done :)
aa556e42a3808ae93ac6a6e1a2d50a1411b0e521

**Pull request merged**
